apiVersion: "v1"
kind: "Service"
metadata:
  name: "microblog-backend"
  labels:
    app: "microblog-backend"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8000
  selector:
    app: "microblog-backend"
  type: "ClusterIP"
