apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "postgres"
  labels:
    app: "postgres"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres"
  template:
    metadata:
      labels:
        app: "postgres"
    spec:
      containers:
        - name: "postgres"
          image: "postgres:12.1-alpine"
          volumeMounts:
            - mountPath: "/var/lib/postgresql"
              name: postgres-data
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: db
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
