apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}
  db: {{ .Values.database.name | b64enc }}
